apiVersion: v1
kind: Service
metadata:
  name: swagger-front
spec:
  selector:
    app: swagger-front
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 8090
    targetPort: 8090
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: swagger-back
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: swagger-front
        tier: frontend
        track: stable
    spec:
      containers:
      - name: swagger-front
        image: "swagger-front:v1"
#        lifecycle:
#          preStop:
#            exec:
#              command: ["/usr/sbin/nginx","-s","quit"]